"""Add MngIndicatorsFeatures table and relationships

Revision ID: 11c21a19c29e
Revises: 
Create Date: 2026-01-29 08:26:34.868825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c21a19c29e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mng_indicators_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_indicator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('RECOMMENDATION', 'FEATURE', name='indicatorfeaturetype'), nullable=False),
    sa.ForeignKeyConstraint(['country_indicator_id'], ['mng_country_indicator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'climate_historical_indicator', 'mng_indicators', ['indicator_id'], ['id'])
    op.create_foreign_key(None, 'historical_agroclimatic_indicator', 'mng_indicators', ['indicator_id'], ['id'])
    op.create_foreign_key(None, 'mng_admin_2', 'mng_admin_1', ['admin_1_id'], ['id'])
    op.create_foreign_key(None, 'mng_country_indicator', 'mng_indicators', ['indicator_id'], ['id'])
    op.create_foreign_key(None, 'mng_location', 'mng_admin_2', ['admin_2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mng_location', type_='foreignkey')
    op.drop_constraint(None, 'mng_country_indicator', type_='foreignkey')
    op.drop_constraint(None, 'mng_admin_2', type_='foreignkey')
    op.drop_constraint(None, 'historical_agroclimatic_indicator', type_='foreignkey')
    op.drop_constraint(None, 'climate_historical_indicator', type_='foreignkey')
    op.drop_table('mng_indicators_features')
    # ### end Alembic commands ###
