"""Add index

Revision ID: 5eb3fabe7aa8
Revises: a41a6a421185
Create Date: 2026-02-19 15:26:06.148343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb3fabe7aa8'
down_revision: Union[str, Sequence[str], None] = 'a41a6a421185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_climatology_location_measure_month', 'climate_historical_climatology', ['location_id', 'measure_id', 'month'], unique=True)
    op.create_index('ix_daily_date', 'climate_historical_daily', ['date'], unique=False)
    op.create_index('ix_daily_location', 'climate_historical_daily', ['location_id'], unique=False)
    op.create_index('ix_daily_location_date', 'climate_historical_daily', ['location_id', 'date'], unique=False)
    op.create_index('ix_daily_location_measure', 'climate_historical_daily', ['location_id', 'measure_id'], unique=False)
    op.create_index('ix_daily_location_measure_date', 'climate_historical_daily', ['location_id', 'measure_id', 'date'], unique=True)
    op.create_index('ix_monthly_date', 'climate_historical_monthly', ['date'], unique=False)
    op.create_index('ix_monthly_location', 'climate_historical_monthly', ['location_id'], unique=False)
    op.create_index('ix_monthly_location_date', 'climate_historical_monthly', ['location_id', 'date'], unique=False)
    op.create_index('ix_monthly_location_measure', 'climate_historical_monthly', ['location_id', 'measure_id'], unique=False)
    op.create_index('ix_monthly_location_measure_date', 'climate_historical_monthly', ['location_id', 'measure_id', 'date'], unique=True)
    op.alter_column('mng_location', 'machine_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.create_index('ix_location_admin2', 'mng_location', ['admin_2_id'], unique=False)
    op.create_index('ix_location_ext_id', 'mng_location', ['ext_id'], unique=False)
    op.create_index('ix_location_machine_name', 'mng_location', ['machine_name'], unique=False)
    op.create_index('ix_location_source', 'mng_location', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_source', table_name='mng_location')
    op.drop_index('ix_location_machine_name', table_name='mng_location')
    op.drop_index('ix_location_ext_id', table_name='mng_location')
    op.drop_index('ix_location_admin2', table_name='mng_location')
    op.alter_column('mng_location', 'machine_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index('ix_monthly_location_measure_date', table_name='climate_historical_monthly')
    op.drop_index('ix_monthly_location_measure', table_name='climate_historical_monthly')
    op.drop_index('ix_monthly_location_date', table_name='climate_historical_monthly')
    op.drop_index('ix_monthly_location', table_name='climate_historical_monthly')
    op.drop_index('ix_monthly_date', table_name='climate_historical_monthly')
    op.drop_index('ix_daily_location_measure_date', table_name='climate_historical_daily')
    op.drop_index('ix_daily_location_measure', table_name='climate_historical_daily')
    op.drop_index('ix_daily_location_date', table_name='climate_historical_daily')
    op.drop_index('ix_daily_location', table_name='climate_historical_daily')
    op.drop_index('ix_daily_date', table_name='climate_historical_daily')
    op.drop_index('ix_climatology_location_measure_month', table_name='climate_historical_climatology')
    # ### end Alembic commands ###
